9.1.1 평균
--

In [4]:
import numpy as np

from sklearn.datasets import make_blobs

In [5]:
blob_centers = np.array(
    [[ 0.2,  2.3],
     [-1.5 ,  2.3],
     [-2.8,  1.8],
     [-2.8,  2.8],
     [-2.8,  1.3]])
blob_std = np.array([0.4, 0.3, 0.1, 0.1, 0.1])

In [6]:
X, y = make_blobs(n_samples=2000, centers=blob_centers,
                  cluster_std=blob_std, random_state=7)

In [7]:
from sklearn.cluster import KMeans
k = 5
kmeans = KMeans(n_clusters=k)
y_pred = kmeans.fit_predict(X)

In [8]:
y_pred

array([0, 4, 3, ..., 2, 3, 4], dtype=int32)

In [9]:
y_pred is kmeans.labels_

True

In [11]:
kmeans.cluster_centers_

array([[-2.80037642,  1.30082566],
       [-1.46679593,  2.28585348],
       [-2.79290307,  2.79641063],
       [ 0.20876306,  2.25551336],
       [-2.80389616,  1.80117999]])

In [12]:
X_new = np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])

In [13]:
kmeans.predict(X_new)

array([3, 3, 2, 2], dtype=int32)

In [14]:
kmeans.transform(X_new)

array([[2.88633901, 1.49439034, 2.9042344 , 0.32995317, 2.81093633],
       [5.84236351, 4.4759332 , 5.84739223, 2.80290755, 5.80730058],
       [1.71086031, 1.69136631, 0.29040966, 3.29399768, 1.21475352],
       [1.21567622, 1.54808703, 0.36159148, 3.21806371, 0.72581411]])

### 센트로이트 초기화 방법

In [16]:
good_init = np.array([[-3, 3], [-3, 2], [-3, 1], [-1, 2], [0, 2]])
kmeans = KMeans(n_clusters=5, init=good_init, n_init=1)

In [22]:
kmeans.fit(X)
kmeans.inertia_

211.5985372581684

### k-평균 속도 개선과 미니배치 k-평균

In [23]:
from sklearn.cluster import MiniBatchKMeans

minibatch_kmeans = MiniBatchKMeans(n_clusters=5)
minibatch_kmeans.fit(X)

MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
                init_size=None, max_iter=100, max_no_improvement=10,
                n_clusters=5, n_init=3, random_state=None,
                reassignment_ratio=0.01, tol=0.0, verbose=0)

### 최적의 클러스터 개수 찾기

In [24]:
from sklearn.metrics import silhouette_score

In [25]:
silhouette_score(X, kmeans.labels_)

0.655517642572828

### 9.1.3 군집을 사용한 이미지 분할